const ROLES = Object.freeze({
  DIRECTOR: 'director',
  ADMIN: 'admin',
  EMPLOYEE: 'employee'
});

const IDEA_STATUSES = Object.freeze({
  PENDING_MODERATION: 'pending_moderation',
  VOTING: 'voting',
  DIRECTOR_REVIEW: 'director_review',
  REJECTED_BY_ADMIN: 'rejected_by_admin',
  REJECTED_BY_VOTE: 'rejected_by_vote',
  APPROVED_BY_DIRECTOR: 'approved_by_director',
  REJECTED_BY_DIRECTOR: 'rejected_by_director'
});

const ACTIVE_IDEA_STATUSES = new Set([
  IDEA_STATUSES.PENDING_MODERATION,
  IDEA_STATUSES.VOTING,
  IDEA_STATUSES.DIRECTOR_REVIEW
]);

const ARCHIVE_IDEA_STATUSES = new Set([
  IDEA_STATUSES.REJECTED_BY_ADMIN,
  IDEA_STATUSES.REJECTED_BY_VOTE,
  IDEA_STATUSES.APPROVED_BY_DIRECTOR,
  IDEA_STATUSES.REJECTED_BY_DIRECTOR
]);

const IDEA_MONTHLY_LIMIT = 3;
const VOTE_APPROVAL_PERCENT = 50;
const SESSION_TTL_HOURS = 24 * 7;

module.exports = {
  ACTIVE_IDEA_STATUSES,
  ARCHIVE_IDEA_STATUSES,
  IDEA_MONTHLY_LIMIT,
  IDEA_STATUSES,
  ROLES,
  SESSION_TTL_HOURS,
  VOTE_APPROVAL_PERCENT
};
